plugins {
	id 'org.jetbrains.kotlin.jvm' version '1.9.25'
	id 'org.jetbrains.kotlin.plugin.spring' version '1.9.25'
	id 'org.springframework.boot' version '3.4.6'
	id 'io.spring.dependency-management' version '1.1.7'
	id "org.jlleitschuh.gradle.ktlint" version "12.1.1"
}

group = 'com.notivest'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Core Spring Boot
	implementation "org.springframework.boot:spring-boot-starter-web"
	implementation "org.springframework.boot:spring-boot-starter-webflux"   // WebClient
	implementation "org.springframework.boot:spring-boot-starter-actuator"
	
	// Kotlin support
	implementation "org.jetbrains.kotlin:kotlin-reflect"
	implementation "com.fasterxml.jackson.module:jackson-module-kotlin"
	
	
	// Test dependencies
	testImplementation "org.springframework.boot:spring-boot-starter-test"
	testImplementation "com.squareup.okhttp3:mockwebserver:4.12.0"
	testImplementation "org.springframework.boot:spring-boot-starter-webflux" // For WebTestClient
	testImplementation "org.mockito.kotlin:mockito-kotlin:5.2.1"
	testImplementation "org.jetbrains.kotlin:kotlin-test-junit5"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher"

    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'

    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
}

kotlin {
	compilerOptions {
		freeCompilerArgs.addAll '-Xjsr305=strict'
	}
}

tasks.named('test') {
	useJUnitPlatform()
}